image:
  repository: victorbutkov/demo-app
  tag: 48e7a875418609e3e9dfaaea849af061c840bee7

replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  serviceName: dashboard-ui-service

labels:
  app: demo-flask-app

appName: dashboard-ui

ingress:
  enabled: false
  host: dashboard-ui.local
  name: dashboard-ui-ingress