image:
  repository: victorbutkov/demo-app
  tag: 9c5c38c054e5de7027d97a71fcab3d57a2597009

replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  serviceName: dashboard-ui-service

labels:
  app: demo-flask-app

appName: dashboard-ui

ingress:
  enabled: false
  host: dashboard-ui.local
  name: dashboard-ui-ingress